FROM python:3.12-slim

COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip wheel setuptools
RUN python3 -m pip install -r requirements.txt

COPY . /catbot
RUN cd /catbot && python3 -m pip install .

WORKDIR /catbot
